# General options
disableHopper: true
preventZeroOutput: true

# Items
bucket:
    id: BUCKET
    rewardid: IRON_INGOT
    rewardamount: 3
    maxdura: 0
    extradura: 0
    calcdura: false